import { getPreset, listPresets } from '../visualization/presetRegistry.js';
import { validateScript } from '../visualization/scriptValidator.js';
import { getModelAdapter } from '../model/modelRegistry.js';
import { scriptError } from '../visualization/scriptErrors.js';

// Preset-first, rule-based script generation for PR C. No LLM is required:
// the generator inspects the goal, the model capabilities and the available
// presets, then picks:
//   1. an exact preset;
//   2. a preset + parameter modification;
//   3. a generated minimal script from the visualization toolkit.
// An external generator (e.g. an LLM adapter) can be injected and its output
// still goes through the same validation + dry-run pipeline.

const PARAMETER_RULES = [
  {
    match: /intro|入门|直觉|开始|first|begin/i,
    mode: 'preset',
  },
  {
    match: /learning rate|学习率|lr|发散|diverg|太高|过高/i,
    adapter: 'linear-regression',
    presetId: 'linear-regression.intuition',
    parameters: { showResiduals: true, showBestFit: true },
    mode: 'parameterized',
  },
  {
    match: /k\s*=\s*([0-9]+)|邻居|neighbor|k 比较|k ?compar/i,
    adapter: 'knn',
    presetId: 'knn.intro',
    parametersFromGoal: (goal) => {
      const match = /k\s*=\s*([0-9]+)/i.exec(goal);
      return match ? { k: Number(match[1]) } : { showNeighborOrder: true };
    },
    mode: 'parameterized',
  },
  {
    match: /分类|classif|解释|explain|适合|slice|切片|data/i,
    adapter: 'knn',
    presetId: 'knn.intro',
    parameters: { showDecisionRegions: true },
    mode: 'parameterized',
  },
];

function parameterizePreset(preset, parameters, mode) {
  const script = structuredClone(preset);
  script.id = `${preset.id}-${mode}`;
  script.steps = [
    {
      id: `param-${Object.keys(parameters).join('-') || 'controls'}`,
      setControl: parameters,
      durationMs: 300,
    },
    ...script.steps,
  ];
  return script;
}

function generateMinimalScript(adapterId, presets) {
  const base = presets.find((preset) => preset.model.adapter === adapterId)
    ?? (adapterId === 'knn' ? getPreset('knn.intro') : getPreset('linear-regression.intuition'));
  if (!base) throw scriptError('SCRIPT_UNKNOWN_MODEL', { model: adapterId });
  const script = structuredClone(base);
  script.id = `${adapterId}-generated`;
  script.steps = [
    { id: 'show', show: script.primitives[0]?.id ?? script.layout.stage[0], durationMs: 300 },
    { id: 'wait', wait: true, durationMs: 400 },
  ];
  return script;
}

function matchRule(goal) {
  for (const rule of PARAMETER_RULES) {
    if (rule.match.test(goal)) return rule;
  }
  return null;
}

// `externalGenerator` is an optional function (goal, context) => { script }.
// Its output always passes validateScript + the caller's dry run.
export function generateVisualizationScript({ goal, constraints = {}, adapterId, presets, externalGenerator }) {
  if (externalGenerator) {
    const produced = externalGenerator(goal, { adapterId, constraints, presets });
    if (!produced || typeof produced.script !== 'object') {
      throw scriptError('INVALID_SCRIPT', { reason: 'generator returned no script' });
    }
    validateScript(produced.script);
    return {
      mode: produced.mode ?? 'generated',
      script: produced.script,
      rationale: produced.rationale ?? 'Generated by the external generator.',
    };
  }

  const available = (presets ?? listPresets()).map((preset) => getPreset(preset.id)).filter(Boolean);
  const goalText = String(goal ?? '');
  const rule = matchRule(goalText);
  const currentAdapter = adapterId;

  if (rule?.mode === 'preset') {
    const preset = available.find((item) => item.model.adapter === currentAdapter) ?? available[0];
    if (preset) {
      return { mode: 'preset', script: structuredClone(preset), rationale: `Exact preset ${preset.id} for "${goal}".` };
    }
  }
  if (rule?.mode === 'parameterized') {
    const preset = available.find((item) => item.id === rule.presetId) ?? available.find((item) => item.model.adapter === rule.adapter);
    if (preset) {
      const parameters = rule.parametersFromGoal ? rule.parametersFromGoal(goalText) : rule.parameters;
      const script = parameterizePreset(preset, parameters, 'parameterized');
      validateScript(script);
      return {
        mode: 'parameterized',
        script,
        rationale: `Preset ${preset.id} parameterized with ${JSON.stringify(parameters)} for "${goal}".`,
      };
    }
  }

  const script = generateMinimalScript(currentAdapter, available);
  validateScript(script);
  return {
    mode: 'generated',
    script,
    rationale: `Generated a minimal valid script from the ${currentAdapter} visualization toolkit for "${goal}".`,
  };
}
