import type { PipelineEdge, PipelineNode } from '../types';

function interpolate(template: string, parameters: Record<string, number | string>) {
  return template.replace(/\{(\w+)\}/g, (_, key: string) => String(parameters[key] ?? `{${key}}`));
}

export function compilePipelineToPyTorch(nodes: PipelineNode[], edges: PipelineEdge[]) {
  const nodeById = new Map(nodes.map((node) => [node.id, node]));
  const indegree = new Map(nodes.map((node) => [node.id, 0]));
  const outgoing = new Map<string, string[]>();

  for (const edge of edges) {
    outgoing.set(edge.source, [...(outgoing.get(edge.source) ?? []), edge.target]);
    indegree.set(edge.target, (indegree.get(edge.target) ?? 0) + 1);
  }

  const queue = nodes.filter((node) => indegree.get(node.id) === 0).map((node) => node.id);
  const ordered: PipelineNode[] = [];

  while (queue.length > 0) {
    const id = queue.shift()!;
    const node = nodeById.get(id);
    if (!node) continue;
    ordered.push(node);

    for (const target of outgoing.get(id) ?? []) {
      const next = (indegree.get(target) ?? 0) - 1;
      indegree.set(target, next);
      if (next === 0) queue.push(target);
    }
  }

  if (ordered.length !== nodes.length) {
    throw new Error('Pipeline graph contains a cycle. Please remove circular connections before exporting.');
  }

  const sections = ordered.map((node, index) => [
    `# Step ${index + 1}: ${node.data.manifest.name.en}`,
    interpolate(node.data.manifest.pytorch_template, node.data.parameters),
  ].join('\n'));

  return [
    '# Generated by VOLK-ML',
    '# Review tensor shapes and dataset bindings before running.',
    '',
    ...sections,
    '',
  ].join('\n\n');
}
