export const exampleMetadata = [
  {
    id: 'linear-trend-concept',
    file: 'linear-trend-concept.volkml.json',
    titleKey: 'example.linearTrend.title',
    descriptionKey: 'example.linearTrend.description',
    role: 'concept',
    concept: 'linear-regression',
    runnable: true,
    exportable: true,
    datasetId: 'linear-trend',
    visualFeatureColumns: ['x'],
    teachingContract: {
      minRows: 120,
      maxRows: 200,
      expectedBrowserResult: { metric: 'r2', min: 0.9 },
      residualNonZero: true,
    },
  },
  {
    id: 'house-price-applied',
    file: 'house-price-applied.volkml.json',
    titleKey: 'example.housePrice.title',
    descriptionKey: 'example.housePrice.description',
    role: 'applied',
    concept: 'multiple-linear-regression',
    runnable: true,
    exportable: true,
    datasetId: 'house-price',
    visualFeatureColumns: ['area_sqm'],
    teachingContract: {
      minRows: 160,
      maxRows: 400,
      minFeatures: 3,
      expectedBrowserResult: { metric: 'r2', min: 0.92, max: 0.9999 },
    },
  },
  {
    id: 'knn-neighborhood-concept',
    file: 'knn-neighborhood-concept.volkml.json',
    titleKey: 'example.knnNeighborhood.title',
    descriptionKey: 'example.knnNeighborhood.description',
    role: 'concept',
    concept: 'nonlinear-decision-boundary',
    runnable: true,
    exportable: false,
    datasetId: 'knn-neighborhood',
    visualFeatureColumns: ['x1', 'x2'],
    teachingContract: {
      minRows: 160,
      maxRows: 240,
      classBalance: { min: 0.45, max: 0.55 },
      expectedBrowserResult: { metric: 'accuracy', min: 0.88 },
      kSensitivity: true,
    },
  },
  {
    id: 'iris-applied',
    file: 'iris-applied.volkml.json',
    titleKey: 'example.iris.title',
    descriptionKey: 'example.iris.description',
    role: 'applied',
    concept: 'overlapping-classes',
    runnable: true,
    exportable: false,
    datasetId: 'iris',
    visualFeatureColumns: ['petal_length', 'petal_width'],
    teachingContract: {
      minRows: 150,
      maxRows: 300,
      classBalance: { min: 0.3, max: 0.37 },
      maxSingleFeatureThresholdAccuracy: 0.95,
      expectedBrowserResult: { metric: 'accuracy', min: 0.8, max: 0.97 },
    },
  },
  {
    id: 'xor-mlp-concept',
    file: 'xor-mlp-concept.volkml.json',
    titleKey: 'example.xorMlp.title',
    descriptionKey: 'example.xorMlp.description',
    role: 'concept',
    concept: 'nonlinear-decision-boundary',
    runnable: true,
    exportable: true,
    datasetId: 'xor-mlp-concept',
    visualFeatureColumns: ['x1', 'x2'],
    teachingContract: {
      minRows: 32,
      maxRows: 64,
      classBalance: { min: 0.45, max: 0.55 },
      maxSingleFeatureThresholdAccuracy: 0.8,
      maxLinearSeparatorAccuracy: 0.8,
      expectedBrowserResult: { metric: 'accuracy', min: 0.88 },
      requiredNonlinearity: true,
    },
  },
  {
    id: 'spam-applied-mlp',
    file: 'spam-applied-mlp.volkml.json',
    titleKey: 'example.spamMlp.title',
    descriptionKey: 'example.spamMlp.description',
    role: 'applied',
    concept: 'feature-interactions',
    runnable: true,
    exportable: true,
    datasetId: 'spam',
    visualFeatureColumns: ['link_count', 'sender_reputation'],
    teachingContract: {
      minRows: 320,
      maxRows: 500,
      minFeatures: 8,
      classBalance: { min: 0.35, max: 0.65 },
      maxSingleFeatureThresholdAccuracy: 0.86,
      expectedBrowserResult: { metric: 'accuracy', min: 0.8 },
    },
  },
  {
    id: 'energy-demand-mlp',
    file: 'energy-demand-mlp.volkml.json',
    titleKey: 'example.energyMlp.title',
    descriptionKey: 'example.energyMlp.description',
    role: 'applied',
    concept: 'nonlinear-regression',
    runnable: true,
    exportable: true,
    datasetId: 'energy',
    visualFeatureColumns: ['temperature', 'occupancy'],
    teachingContract: {
      minRows: 240,
      maxRows: 500,
      minFeatures: 5,
      expectedBrowserResult: { metric: 'r2', min: 0.82 },
      requiredNonlinearity: true,
      linearBaselineGap: 0.12,
    },
  },
  {
    id: 'peak-demand-custom-loss',
    file: 'peak-demand-custom-loss.volkml.json',
    titleKey: 'example.peakDemand.title',
    descriptionKey: 'example.peakDemand.description',
    role: 'applied',
    concept: 'custom-loss',
    runnable: false,
    exportable: true,
    datasetId: 'energy',
    visualFeatureColumns: ['temperature', 'occupancy'],
    teachingContract: {
      minRows: 240,
      maxRows: 500,
      minFeatures: 5,
      requiredNonlinearity: true,
    },
    limitationsKey: 'example.peakDemand.limitations',
  },
  {
    id: 'diabetes-risk-mlp',
    file: 'diabetes-risk-mlp.volkml.json',
    titleKey: 'example.diabetesMlp.title',
    descriptionKey: 'example.diabetesMlp.description',
    role: 'applied',
    concept: 'feature-interactions',
    runnable: false,
    exportable: true,
    datasetId: 'diabetes',
    visualFeatureColumns: ['glucose', 'bmi'],
    teachingContract: {
      minRows: 350,
      maxRows: 600,
      minFeatures: 7,
      classBalance: { min: 0.25, max: 0.6 },
      maxSingleFeatureThresholdAccuracy: 0.88,
    },
    limitationsKey: 'example.diabetesMlp.limitations',
  },
  {
    id: 'shape-cnn',
    file: 'shape-cnn.volkml.json',
    titleKey: 'example.shapeCnn.title',
    descriptionKey: 'example.shapeCnn.description',
    role: 'architecture-sketch',
    concept: 'convolutional-features',
    runnable: false,
    exportable: true,
    visualFeatureColumns: [],
    teachingContract: {},
    limitationsKey: 'example.shapeCnn.limitations',
  },
  {
    id: 'user-item-embedding',
    file: 'user-item-embedding.volkml.json',
    titleKey: 'example.userItemEmbedding.title',
    descriptionKey: 'example.userItemEmbedding.description',
    role: 'architecture-sketch',
    concept: 'embedding-representation',
    runnable: false,
    exportable: true,
    visualFeatureColumns: [],
    teachingContract: {},
    limitationsKey: 'example.userItemEmbedding.limitations',
  },
  {
    id: 'sentiment-lstm',
    file: 'sentiment-lstm.volkml.json',
    titleKey: 'example.sentimentLstm.title',
    descriptionKey: 'example.sentimentLstm.description',
    role: 'architecture-sketch',
    concept: 'sequence-modeling',
    runnable: false,
    exportable: true,
    visualFeatureColumns: [],
    teachingContract: {},
    limitationsKey: 'example.sentimentLstm.limitations',
  },
];
