export const exampleMetadata = [
  {
    id: 'housePrice',
    file: 'house-price-regression.volkml.json',
    titleKey: 'example.housePrice.title',
    descriptionKey: 'example.housePrice.description',
    taskKey: 'examples.task.regression',
    runnable: true,
    exportable: true,
    componentIds: ['tabular_data_node', 'train_test_split_node', 'linear_regression_node', 'gradient_descent_node', 'evaluate_node', 'predictor_node'],
  },
  {
    id: 'irisKnn',
    file: 'iris-knn-classification.volkml.json',
    titleKey: 'example.irisKnn.title',
    descriptionKey: 'example.irisKnn.description',
    taskKey: 'examples.task.classification',
    runnable: true,
    exportable: false,
    componentIds: ['tabular_data_node', 'knn_node', 'evaluate_classification_node', 'predictor_node'],
  },
  {
    id: 'spamMlp',
    file: 'spam-mlp-classification.volkml.json',
    titleKey: 'example.spamMlp.title',
    descriptionKey: 'example.spamMlp.description',
    taskKey: 'examples.task.classification',
    runnable: true,
    exportable: true,
    componentIds: ['tabular_data_node', 'train_test_split_node', 'tensor_input_node', 'dense_node', 'relu_node', 'softmax_node', 'model_output_node', 'cross_entropy_loss_node', 'sgd_optimizer_node', 'supervised_trainer_node', 'evaluate_classification_node', 'predictor_node'],
  },
  {
    id: 'energyMlp',
    file: 'energy-demand-mlp.volkml.json',
    titleKey: 'example.energyMlp.title',
    descriptionKey: 'example.energyMlp.description',
    taskKey: 'examples.task.regression',
    runnable: false,
    exportable: true,
    componentIds: ['tabular_data_node', 'train_test_split_node', 'tensor_input_node', 'dense_node', 'model_output_node', 'custom_loss_node', 'adamw_optimizer_node', 'supervised_trainer_node', 'evaluate_node'],
  },
  {
    id: 'diabetesMlp',
    file: 'diabetes-risk-mlp.volkml.json',
    titleKey: 'example.diabetesMlp.title',
    descriptionKey: 'example.diabetesMlp.description',
    taskKey: 'examples.task.binary',
    runnable: false,
    exportable: true,
    componentIds: ['tabular_data_node', 'train_test_split_node', 'tensor_input_node', 'mlp_block_node', 'residual_mlp_block_node', 'layer_norm_node', 'gelu_node', 'sigmoid_node', 'dense_node', 'model_output_node', 'binary_cross_entropy_loss_node', 'adam_optimizer_node', 'supervised_trainer_node', 'evaluate_classification_node'],
  },
  {
    id: 'catDogCnn',
    file: 'cat-dog-cnn.volkml.json',
    titleKey: 'example.catDogCnn.title',
    descriptionKey: 'example.catDogCnn.description',
    taskKey: 'examples.task.cnn',
    runnable: false,
    exportable: true,
    componentIds: ['tensor_input_node', 'reshape_node', 'conv_block_node', 'flatten_node', 'dense_node', 'model_output_node'],
  },
  {
    id: 'movieRec',
    file: 'movie-recommendation.volkml.json',
    titleKey: 'example.movieRec.title',
    descriptionKey: 'example.movieRec.description',
    taskKey: 'examples.task.embedding',
    runnable: false,
    exportable: true,
    componentIds: ['tensor_input_node', 'embedding_node', 'concatenate_node', 'dense_node', 'model_output_node'],
  },
  {
    id: 'sentimentLstm',
    file: 'sentiment-lstm.volkml.json',
    titleKey: 'example.sentimentLstm.title',
    descriptionKey: 'example.sentimentLstm.description',
    taskKey: 'examples.task.sequence',
    runnable: false,
    exportable: true,
    componentIds: ['tensor_input_node', 'embedding_node', 'lstm_node', 'dropout_node', 'dense_node', 'tanh_node', 'model_output_node'],
  },
];
