const encoder = new TextEncoder();

function sourceSpan(sourceLines, startIndex, endIndex) {
  let byteOffset = 0;
  for (let index = 0; index < startIndex; index += 1) {
    byteOffset += encoder.encode(sourceLines[index]).length + 1;
  }
  const startByte = byteOffset;
  for (let index = startIndex; index < endIndex; index += 1) {
    byteOffset += encoder.encode(sourceLines[index]).length + 1;
  }
  byteOffset += encoder.encode(sourceLines[endIndex]).length;
  return {
    startByte,
    endByte: byteOffset,
    startLine: startIndex + 1,
    endLine: endIndex + 1,
  };
}

/** Emits the canonical Python lines and captures ownership at the emission site. */
export class SourceMapWriter {
  constructor(irVersion) {
    this.lines = [];
    this.annotations = [];
    this.addLines([
      `# Generated by VOLK-ML IR v${irVersion}`,
      '# Review tensor shapes and dataset bindings before running.',
      '',
    ], { compilerRole: 'generated-header' });
  }

  addLines(lines, annotation = {}) {
    if (!Array.isArray(lines) || lines.some((line) => typeof line !== 'string')) {
      throw new Error('SOURCE_EXPORT_EMISSION_INVALID');
    }
    if (!lines.length) return;
    const startIndex = this.lines.length;
    this.lines.push(...lines);
    const endIndex = this.lines.length - 1;
    const hasSource = lines.some((line) => line.length > 0);
    if (!hasSource) return;
    const { role, nodeOrigins = [], edgeRefs = [], compilerRole } = annotation;
    if ((nodeOrigins.length || edgeRefs.length) && typeof role !== 'string') {
      throw new Error('SOURCE_EXPORT_EMISSION_INVALID');
    }
    if (compilerRole !== undefined && typeof compilerRole !== 'string') {
      throw new Error('SOURCE_EXPORT_EMISSION_INVALID');
    }
    this.annotations.push({ startIndex, endIndex, role, nodeOrigins, edgeRefs, compilerRole });
  }

  finish() {
    const sourceLines = [...this.lines, ''];
    const code = sourceLines.join('\n');
    const nodeConstructs = [];
    const edgeConstructs = [];
    const compilerConstructs = [];
    this.annotations.forEach((annotation) => {
      const span = sourceSpan(
        this.lines,
        annotation.startIndex,
        annotation.endIndex,
      );
      annotation.nodeOrigins.forEach((origin) => nodeConstructs.push({
        ...origin,
        role: annotation.role,
        span,
        edgeRefs: annotation.edgeRefs.map((edge) => edge.id),
      }));
      annotation.edgeRefs.forEach((edge) => edgeConstructs.push({ edge, role: annotation.role, span }));
      if (annotation.compilerRole) compilerConstructs.push({ role: annotation.compilerRole, span });
    });
    return { code, nodeConstructs, edgeConstructs, compilerConstructs };
  }
}
