const text = (en, zh) => ({ en, zh });

const lesson = ({
  intuition,
  intuitionZh,
  principle,
  principleZh,
  formula,
  formulaZh = formula,
  example,
  exampleZh,
  visual = 'flow',
}) => ({
  intuition: text(intuition, intuitionZh),
  principle: text(principle, principleZh),
  formula: text(formula, formulaZh),
  example: text(example, exampleZh),
  visual,
});

export const tutorialByOp = {
  tabular_data: lesson({
    intuition: 'Think of this as the tray that brings rows and columns into the pipeline.',
    intuitionZh: '可以把它理解成把一行行、一列列数据送进管线的托盘。',
    principle: 'A table represents samples as rows and variables as columns. Feature columns become model inputs and one target column becomes the answer to learn.',
    principleZh: '表格用行表示样本、用列表示变量。特征列成为模型输入，目标列是模型要学习的答案。',
    formula: 'X ∈ ℝⁿˣᵈ,  y ∈ ℝⁿ',
    example: '100 students × study hours and practice tests → exam score.',
    exampleZh: '100 名学生 × 学习时长和练习次数 → 考试分数。',
    visual: 'table',
  }),
  train_test_split: lesson({
    intuition: 'Keep part of the data hidden while learning, then use it as a fresh exam.',
    intuitionZh: '学习时先藏起一部分数据，最后把它当作一场没见过的考试。',
    principle: 'Training data fits parameters; test data estimates how well the learned rule generalizes to unseen samples.',
    principleZh: '训练集用于拟合参数，测试集用于估计学到的规律对未见样本的泛化能力。',
    formula: 'D = Dtrain ∪ Dtest,  Dtrain ∩ Dtest = ∅',
    example: 'An 80/20 split sends 80 rows to training and keeps 20 rows for evaluation.',
    exampleZh: '80/20 划分会用 80 行训练，并保留 20 行做评估。',
    visual: 'split',
  }),
  linear_regression: lesson({
    intuition: 'Fit the straight plane that best follows the trend in the data.',
    intuitionZh: '找一条直线或一个平面，尽量贴合数据中的总体趋势。',
    principle: 'Each input feature receives a weight. The weighted sum plus a bias predicts a continuous value.',
    principleZh: '每个输入特征得到一个权重，加权求和后再加偏置，得到连续数值预测。',
    formula: 'ŷ = wᵀx + b',
    example: 'Predict exam score from study hours and practice-test count.',
    exampleZh: '根据学习时长和练习次数预测考试分数。',
    visual: 'scatter',
  }),
  knn_classifier: lesson({
    intuition: 'Ask the nearby known examples to vote on a new sample.',
    intuitionZh: '让新样本附近最相似的已知样本一起投票。',
    principle: 'KNN measures distance to stored samples, selects the k nearest, and returns their majority class.',
    principleZh: 'KNN 计算新样本与已知样本的距离，选择最近的 k 个，再返回多数类别。',
    formula: 'ŷ = mode({yᵢ | xᵢ ∈ Nk(x)})',
    example: 'If four of the five nearest flowers are class A, predict class A.',
    exampleZh: '若最近的 5 朵花中有 4 朵属于 A 类，就预测为 A 类。',
    visual: 'neighbors',
  }),
  gradient_descent: lesson({
    intuition: 'Walk downhill on the loss landscape, one small step at a time.',
    intuitionZh: '在损失函数的山坡上一步步往下走。',
    principle: 'The gradient points toward the steepest increase, so subtracting it moves parameters toward lower loss.',
    principleZh: '梯度指向上升最快的方向，因此减去梯度会让参数朝更低损失移动。',
    formula: 'θₜ₊₁ = θₜ − η∇θL(θₜ)',
    example: 'Repeatedly adjust regression weights until prediction error stops falling.',
    exampleZh: '反复调整回归权重，直到预测误差不再明显下降。',
    visual: 'descent',
  }),
  evaluate_regression: lesson({
    intuition: 'Turn test-set predictions into a readable report card.',
    intuitionZh: '把测试集上的预测结果整理成容易理解的成绩单。',
    principle: 'RMSE measures typical error size; R² measures how much target variation the model explains.',
    principleZh: 'RMSE 衡量典型误差大小；R² 衡量模型解释了多少目标变化。',
    formula: 'RMSE = √mean((y − ŷ)²)',
    formulaZh: 'RMSE = √平均值((y − ŷ)²)',
    example: 'RMSE = 3 means predictions miss the true score by about 3 points on average.',
    exampleZh: 'RMSE 为 3，表示预测通常与真实分数相差约 3 分。',
    visual: 'bars',
  }),
  evaluate_classification: lesson({
    intuition: 'Turn held-out class predictions into a report card for the classifier.',
    intuitionZh: '把留出测试集上的类别预测整理成分类器成绩单。',
    principle: 'Accuracy measures the share of correct predictions. Macro F1 gives every class equal weight by averaging class-level precision and recall.',
    principleZh: '准确率衡量预测正确的比例；宏平均 F1 先分别计算各类别的精确率与召回率，再让每个类别获得相同权重。',
    formula: 'accuracy = correct / total',
    example: 'Eight correct labels among ten test samples produce 80% accuracy.',
    exampleZh: '10 个测试样本中有 8 个类别预测正确，准确率就是 80%。',
    visual: 'bars',
  }),
  interactive_predictor: lesson({
    intuition: 'Give the trained model new values and immediately inspect its answer.',
    intuitionZh: '给训练好的模型输入新数值，立即查看它的回答。',
    principle: 'Inference keeps learned parameters fixed and applies the learned function to a new input.',
    principleZh: '推理阶段固定已经学到的参数，把学习到的函数应用到新输入。',
    formula: 'new x → fθ(x) → ŷ',
    formulaZh: '新输入 x → fθ(x) → ŷ',
    example: 'Enter 6 study hours and 8 practice tests to predict a score.',
    exampleZh: '输入 6 小时学习时间和 8 次练习，预测考试分数。',
    visual: 'flow',
  }),
  tensor_input: lesson({
    intuition: 'Declare the shape of the numbers that will enter a neural network.',
    intuitionZh: '声明即将进入神经网络的一组数字是什么形状。',
    principle: 'A tensor is a multidimensional array. The declared non-batch dimensions constrain downstream layers.',
    principleZh: '张量是多维数组。声明的非批次维度会约束后续网络层。',
    formula: 'x ∈ ℝᴮˣᵈ¹ˣ⋯ˣᵈᵏ',
    example: 'A 28 × 28 grayscale image batch has shape B × 28 × 28 × 1.',
    exampleZh: '一批 28 × 28 灰度图像的形状可写为 B × 28 × 28 × 1。',
    visual: 'tensor',
  }),
  model_output: lesson({
    intuition: 'Mark which final tensor should leave the model.',
    intuitionZh: '标记哪个最终张量是模型真正要输出的结果。',
    principle: 'The compiler walks backward from declared outputs, so only nodes contributing to them become part of the generated model.',
    principleZh: '编译器会从模型输出反向追踪，只有真正参与结果的节点才进入生成模型。',
    formula: 'model(x) = selected output tensor',
    formulaZh: 'model(x) = 选定的输出张量',
    example: 'Choose class logits as the output while leaving debugging branches uncompiled.',
    exampleZh: '把类别 logits 设为输出，而不编译旁边用于试验的孤立分支。',
    visual: 'flow',
  }),
  dense: lesson({
    intuition: 'Let every output unit look at every input feature.',
    intuitionZh: '让每个输出单元都能看到所有输入特征。',
    principle: 'A dense layer learns a matrix of connections and an optional bias vector.',
    principleZh: '全连接层学习一组连接矩阵以及可选的偏置向量。',
    formula: 'y = Wx + b',
    example: 'Convert 32 input features into 64 learned features.',
    exampleZh: '把 32 个输入特征转换为 64 个学习到的特征。',
    visual: 'network',
  }),
  conv2d: lesson({
    intuition: 'Slide a small detector across an image to find the same pattern anywhere.',
    intuitionZh: '让一个小型检测器在图像上滑动，在不同位置寻找相同模式。',
    principle: 'A shared kernel computes local weighted sums, producing feature maps with far fewer parameters than a dense image layer.',
    principleZh: '共享卷积核对局部区域做加权求和，以远少于全连接层的参数生成特征图。',
    formula: 'Yᵢⱼ = ΣₐΣᵦ KₐᵦXᵢ₊ₐ,ⱼ₊ᵦ',
    example: 'A 3 × 3 kernel can learn to respond to vertical edges.',
    exampleZh: '一个 3 × 3 卷积核可以学会对垂直边缘产生响应。',
    visual: 'grid',
  }),
  max_pool2d: lesson({
    intuition: 'Keep the strongest signal in each small image region.',
    intuitionZh: '在图像的每个小区域中只保留最强的信号。',
    principle: 'Max pooling downsamples a feature map by replacing each window with its maximum value.',
    principleZh: '最大池化用窗口内的最大值替代整个窗口，从而缩小特征图。',
    formula: 'Yᵢⱼ = max(Xwindow(i,j))',
    formulaZh: 'Yᵢⱼ = 最大值(X窗口(i,j))',
    example: 'A 2 × 2 window turns four activations [1, 5, 2, 3] into 5.',
    exampleZh: '2 × 2 窗口会把四个激活值 [1, 5, 2, 3] 变成 5。',
    visual: 'pool',
  }),
  flatten: lesson({
    intuition: 'Unroll a multidimensional feature map into one long feature vector.',
    intuitionZh: '把多维特征图摊平成一条长向量。',
    principle: 'Flatten changes shape but preserves every value and its deterministic order.',
    principleZh: '展平只改变形状，不改变任何数值及其确定顺序。',
    formula: 'B × H × W × C → B × (HWC)',
    example: 'A 4 × 4 × 8 feature map becomes a vector of length 128.',
    exampleZh: '4 × 4 × 8 的特征图会变成长度为 128 的向量。',
    visual: 'shape',
  }),
  reshape: lesson({
    intuition: 'Rearrange the container shape without changing the numbers inside.',
    intuitionZh: '改变装数字的容器形状，但不改变里面的数字。',
    principle: 'Input and output must contain the same total number of elements.',
    principleZh: '输入和输出必须拥有相同的元素总数。',
    formula: '∏ input dims = ∏ output dims',
    formulaZh: '∏ 输入维度 = ∏ 输出维度',
    example: 'Reshape a 12-value vector into a 3 × 4 matrix.',
    exampleZh: '把包含 12 个数的向量重塑为 3 × 4 矩阵。',
    visual: 'shape',
  }),
  relu: lesson({
    intuition: 'Pass positive evidence forward and switch negative evidence off.',
    intuitionZh: '让正信号继续通过，把负信号关掉。',
    principle: 'ReLU introduces nonlinearity with a constant positive-side gradient, making deep networks able to learn nonlinear functions.',
    principleZh: 'ReLU 用正半轴上的稳定梯度引入非线性，使深层网络能够学习非线性函数。',
    formula: 'ReLU(x) = max(0, x)',
    example: '[-2, 0.5, 3] becomes [0, 0.5, 3].',
    exampleZh: '[-2, 0.5, 3] 会变成 [0, 0.5, 3]。',
    visual: 'relu',
  }),
  gelu: lesson({
    intuition: 'Smoothly gate values according to how positive and likely they are.',
    intuitionZh: '根据数值的正负程度，以平滑方式决定让多少信号通过。',
    principle: 'GELU multiplies an input by an approximate probability of being selected, avoiding ReLU’s hard corner.',
    principleZh: 'GELU 用近似的“被选择概率”缩放输入，避免 ReLU 的硬折角。',
    formula: 'GELU(x) = xΦ(x)',
    example: 'Commonly used inside Transformer feed-forward blocks.',
    exampleZh: '常用于 Transformer 的前馈网络模块。',
    visual: 'smooth-curve',
  }),
  sigmoid: lesson({
    intuition: 'Squeeze any real number into a probability-like value between 0 and 1.',
    intuitionZh: '把任意实数压缩到 0 和 1 之间，形成类似概率的数值。',
    principle: 'The S-shaped logistic curve is useful for binary probabilities but saturates at large magnitudes.',
    principleZh: 'S 形逻辑曲线适合表达二元概率，但绝对值很大时梯度会饱和。',
    formula: 'σ(x) = 1 / (1 + e⁻ˣ)',
    example: 'A logit of 0 becomes probability 0.5.',
    exampleZh: 'logit 为 0 时会得到概率 0.5。',
    visual: 'sigmoid',
  }),
  tanh: lesson({
    intuition: 'Squeeze values into a zero-centered range from −1 to 1.',
    intuitionZh: '把数值压缩到以 0 为中心的 −1 到 1 区间。',
    principle: 'Tanh is a shifted and scaled sigmoid with odd symmetry.',
    principleZh: 'Tanh 可以看成平移和缩放后的 Sigmoid，并具有奇对称性。',
    formula: 'tanh(x) = (eˣ − e⁻ˣ)/(eˣ + e⁻ˣ)',
    example: 'Often used for candidate states in recurrent networks.',
    exampleZh: '常用于循环神经网络中的候选状态。',
    visual: 'tanh',
  }),
  softmax: lesson({
    intuition: 'Turn competing class scores into probabilities that add up to one.',
    intuitionZh: '把互相竞争的类别分数变成总和为 1 的概率。',
    principle: 'Exponentiation makes larger logits dominate, then normalization forms a categorical distribution.',
    principleZh: '指数运算放大较大的 logits，再通过归一化形成类别分布。',
    formula: 'softmax(zᵢ) = eᶻⁱ / Σⱼeᶻʲ',
    example: 'Scores [2, 1, 0] become probabilities of roughly [0.67, 0.24, 0.09].',
    exampleZh: '分数 [2, 1, 0] 会变成约 [0.67, 0.24, 0.09] 的概率。',
    visual: 'probability',
  }),
  dropout: lesson({
    intuition: 'Randomly hide some neurons during training so the network cannot depend on one shortcut.',
    intuitionZh: '训练时随机遮住一些神经元，防止网络过度依赖某条捷径。',
    principle: 'Independent Bernoulli masks regularize co-adaptation; inference uses the full network with matched scaling.',
    principleZh: '独立伯努利掩码抑制神经元共适应；推理时使用完整网络并保持尺度一致。',
    formula: 'y = m ⊙ x / (1 − p),  m ~ Bernoulli(1 − p)',
    formulaZh: 'y = m ⊙ x / (1 − p),  m ~ 伯努利(1 − p)',
    example: 'Dropout 0.2 hides about 20% of activations each training step.',
    exampleZh: 'Dropout 为 0.2 时，每个训练步骤约隐藏 20% 的激活值。',
    visual: 'dropout',
  }),
  batch_norm1d: lesson({
    intuition: 'Keep feature scales stable using statistics from the current mini-batch.',
    intuitionZh: '利用当前小批次的统计量，让各个特征保持稳定尺度。',
    principle: 'Batch normalization standardizes each feature, then learns a scale and shift.',
    principleZh: '批归一化先标准化每个特征，再学习缩放和平移参数。',
    formula: 'y = γ(x − μB)/√(σ²B + ε) + β',
    example: 'Normalize 64 vector features before the next activation.',
    exampleZh: '在下一激活函数前归一化 64 个向量特征。',
    visual: 'normalize',
  }),
  batch_norm2d: lesson({
    intuition: 'Stabilize each image channel using batch and spatial statistics.',
    intuitionZh: '利用批次和空间统计量稳定图像的每个通道。',
    principle: 'For convolutional maps, statistics are shared across batch and spatial locations for each channel.',
    principleZh: '对于卷积特征图，每个通道会共享批次和空间位置上的统计量。',
    formula: 'μC, σ²C = statistics over B, H, W;  y = γ(X − μC)/√(σ²C + ε) + β',
    formulaZh: 'μC, σ²C = B、H、W 维度上的统计量；y = γ(X − μC)/√(σ²C + ε) + β',
    example: 'Normalize 32 convolutional feature channels before ReLU.',
    exampleZh: '在 ReLU 前归一化 32 个卷积特征通道。',
    visual: 'normalize',
  }),
  layer_norm: lesson({
    intuition: 'Normalize the features inside each individual sample.',
    intuitionZh: '在每个样本内部对特征做归一化。',
    principle: 'Layer normalization computes statistics across selected feature dimensions, independent of other batch samples.',
    principleZh: '层归一化在指定特征维度上计算统计量，不依赖同批次的其他样本。',
    formula: 'y = γ(x − μfeatures)/√(σ²features + ε) + β',
    formulaZh: 'y = γ(x − μ特征)/√(σ²特征 + ε) + β',
    example: 'Normalize a Transformer token’s 768-dimensional representation.',
    exampleZh: '归一化 Transformer 中某个 token 的 768 维表示。',
    visual: 'normalize',
  }),
  embedding: lesson({
    intuition: 'Give every discrete ID a learnable vector meaning.',
    intuitionZh: '给每个离散 ID 分配一个可学习的向量含义。',
    principle: 'Embedding is a trainable lookup table whose rows are updated by gradient descent.',
    principleZh: '嵌入层本质是可训练的查找表，每一行都会通过梯度下降更新。',
    formula: 'E ∈ ℝⱽˣᴰ,  output = E[token_id]',
    formulaZh: 'E ∈ ℝⱽˣᴰ，输出 = E[词元编号]',
    example: 'Map token 42 to a learned 128-dimensional vector.',
    exampleZh: '把 token 42 映射为一个学习到的 128 维向量。',
    visual: 'embedding',
  }),
  lstm: lesson({
    intuition: 'Carry a long-term memory along a sequence while deciding what to keep or forget.',
    intuitionZh: '沿序列传递长期记忆，并不断决定保留什么、忘记什么。',
    principle: 'Input, forget, and output gates control a persistent cell state, reducing ordinary RNN vanishing gradients.',
    principleZh: '输入门、遗忘门和输出门共同控制持续的记忆单元，缓解普通 RNN 的梯度消失。',
    formula: 'cₜ = fₜ⊙cₜ₋₁ + iₜ⊙c̃ₜ',
    example: 'Remember a subject across many words to interpret a later verb.',
    exampleZh: '跨越多个词记住主语，以帮助理解后面的动词。',
    visual: 'sequence',
  }),
  gru: lesson({
    intuition: 'Maintain sequence memory with a simpler pair of gates.',
    intuitionZh: '用更简洁的两组门控维持序列记忆。',
    principle: 'Update and reset gates blend old state with new evidence without a separate cell state.',
    principleZh: '更新门和重置门在旧状态与新信息之间进行融合，不需要独立记忆单元。',
    formula: 'hₜ = (1 − zₜ)⊙hₜ₋₁ + zₜ⊙h̃ₜ',
    example: 'Model a sensor time series with fewer parameters than an LSTM.',
    exampleZh: '用比 LSTM 更少的参数建模传感器时间序列。',
    visual: 'sequence',
  }),
  multihead_attention: lesson({
    intuition: 'Let every sequence position look at other positions from several perspectives.',
    intuitionZh: '让序列中的每个位置从多个角度观察其他位置。',
    principle: 'Queries score keys, normalized scores mix values, and multiple heads learn different relationships.',
    principleZh: '查询向量为键向量打分，归一化权重混合值向量，多头分别学习不同关系。',
    formula: 'Attention(Q,K,V) = softmax(QKᵀ/√d)V',
    example: 'One head tracks syntax while another links repeated entities.',
    exampleZh: '一个注意力头关注句法，另一个连接重复出现的实体。',
    visual: 'attention',
  }),
  add: lesson({
    intuition: 'Combine two equally shaped signals by adding them element by element.',
    intuitionZh: '把两个形状相同的信号逐元素相加。',
    principle: 'Elementwise addition preserves shape and enables residual paths for gradient flow.',
    principleZh: '逐元素相加保持张量形状，并能构建帮助梯度传播的残差路径。',
    formula: 'yᵢ = aᵢ + bᵢ',
    example: '[1, 2] + [3, 4] = [4, 6].',
    exampleZh: '[1, 2] + [3, 4] = [4, 6]。',
    visual: 'merge',
  }),
  concatenate: lesson({
    intuition: 'Place two tensors side by side along one chosen axis.',
    intuitionZh: '沿指定维度把两个张量并排拼在一起。',
    principle: 'All non-concatenated dimensions must match; the selected dimension sizes are summed.',
    principleZh: '除拼接轴外的其他维度必须一致，拼接轴的长度相加。',
    formula: 'shape(y)axis = shape(a)axis + shape(b)axis',
    formulaZh: '形状(y)拼接轴 = 形状(a)拼接轴 + 形状(b)拼接轴',
    example: 'Two 32-feature vectors become one 64-feature vector.',
    exampleZh: '两个 32 维特征向量拼成一个 64 维向量。',
    visual: 'merge',
  }),
  mse_loss: lesson({
    intuition: 'Penalize predictions more strongly when they are far from a numeric target.',
    intuitionZh: '预测值离数值目标越远，惩罚就越强。',
    principle: 'Squaring makes errors positive, differentiable, and increasingly costly as magnitude grows.',
    principleZh: '平方让误差保持非负且可微，并使大误差受到更强惩罚。',
    formula: 'MSE = (1/n)Σᵢ(yᵢ − ŷᵢ)²',
    example: 'Errors 1 and 3 contribute squared costs 1 and 9.',
    exampleZh: '误差 1 和 3 分别产生 1 和 9 的平方损失。',
    visual: 'loss',
  }),
  cross_entropy_loss: lesson({
    intuition: 'Punish a classifier when it assigns low probability to the correct class.',
    intuitionZh: '分类器给正确类别的概率越低，惩罚越大。',
    principle: 'Negative log likelihood compares the predicted categorical distribution with the true class.',
    principleZh: '负对数似然把预测的类别分布与真实类别进行比较。',
    formula: 'L = −log p(correct class)',
    formulaZh: 'L = −log p(正确类别)',
    example: 'Correct-class probability 0.9 gives much less loss than 0.1.',
    exampleZh: '正确类别概率为 0.9 时，损失远小于概率为 0.1。',
    visual: 'loss',
  }),
  binary_cross_entropy_loss: lesson({
    intuition: 'Measure how well one predicted probability matches a yes/no answer.',
    intuitionZh: '衡量一个预测概率与“是/否”答案的匹配程度。',
    principle: 'Binary cross entropy scores both the positive and negative outcomes; logits require a numerically stable combined form.',
    principleZh: '二元交叉熵同时评价正类和负类；若输入是 logits，应使用数值更稳定的组合形式。',
    formula: 'L = −[y log p + (1−y) log(1−p)]',
    example: 'For y = 1, predicting p = 0.95 has small loss.',
    exampleZh: '当 y = 1 时，预测 p = 0.95 会得到较小损失。',
    visual: 'loss',
  }),
  custom_loss: lesson({
    intuition: 'Write the learning objective you want the model to minimize.',
    intuitionZh: '写出你希望模型最小化的学习目标。',
    principle: 'A restricted expression language keeps the loss portable and safe while translating tensor operations to either PyTorch or TensorFlow.',
    principleZh: '受限表达式语言会把张量运算安全地翻译到 PyTorch 或 TensorFlow，同时保持项目可移植。',
    formula: 'L = f(prediction, target)',
    example: 'mean(square(prediction - target)) defines mean squared error. Available functions are mean, sum, abs, square, sqrt, log, exp, and clip.',
    exampleZh: 'mean(square(prediction - target)) 表示均方误差。可用函数包括 mean、sum、abs、square、sqrt、log、exp 和 clip。',
    visual: 'custom-loss',
  }),
  sgd_optimizer: lesson({
    intuition: 'Move parameters directly opposite to the current gradient.',
    intuitionZh: '让参数直接朝当前梯度的反方向移动。',
    principle: 'SGD uses one learning rate for all parameters; momentum can accumulate a smoother velocity.',
    principleZh: 'SGD 用同一学习率更新所有参数；动量可以累积更平滑的移动速度。',
    formula: 'θ ← θ − ηg',
    example: 'A learning rate of 0.01 moves 1% of the gradient each step.',
    exampleZh: '学习率 0.01 表示每一步移动当前梯度的 1%。',
    visual: 'descent',
  }),
  adam_optimizer: lesson({
    intuition: 'Give each parameter an adaptive step size based on recent gradients.',
    intuitionZh: '根据近期梯度，为每个参数分配自适应步长。',
    principle: 'Adam tracks moving averages of the gradient and squared gradient, combining momentum with per-parameter scaling.',
    principleZh: 'Adam 跟踪梯度及其平方的移动平均，将动量与逐参数缩放结合起来。',
    formula: 'θ ← θ − η m̂/(√v̂ + ε)',
    example: 'Sparse or differently scaled features receive more balanced updates.',
    exampleZh: '稀疏特征或尺度不同的特征可以得到更均衡的更新。',
    visual: 'descent',
  }),
  adamw_optimizer: lesson({
    intuition: 'Use Adam’s adaptive steps while shrinking weights in a separate, controlled way.',
    intuitionZh: '使用 Adam 的自适应更新，同时以独立且可控的方式缩小权重。',
    principle: 'AdamW decouples weight decay from the gradient-based Adam update, giving clearer regularization behavior.',
    principleZh: 'AdamW 把权重衰减与 Adam 的梯度更新解耦，使正则化行为更清晰。',
    formula: 'θ ← θ − η·AdamUpdate − ηλθ',
    formulaZh: 'θ ← θ − η·Adam更新量 − ηλθ',
    example: 'Weight decay 0.01 gently discourages unnecessarily large weights.',
    exampleZh: '权重衰减 0.01 会温和地抑制不必要的大权重。',
    visual: 'descent',
  }),
  supervised_trainer: lesson({
    intuition: 'Bring the data, model, loss, and optimizer together in one explicit training step.',
    intuitionZh: '把数据、模型、损失函数和优化器汇合到一个明确的训练步骤中。',
    principle: 'Each batch runs a forward pass, measures loss against the target, differentiates that loss, and lets the optimizer update model parameters.',
    principleZh: '每个批次先完成前向计算，再用目标值计算损失、求取梯度，并由优化器更新模型参数。',
    formula: 'batch → prediction → loss → gradients → parameter update',
    formulaZh: '批次 → 预测 → 损失 → 梯度 → 参数更新',
    example: 'Connect Train/Test Split, Model Output, Custom Loss, and Adam to export a complete training loop.',
    exampleZh: '连接训练/测试集划分、模型输出、自定义损失函数和 Adam，即可导出完整训练循环。',
    visual: 'trainer',
  }),
  mlp_block: lesson({
    intuition: 'Bundle a dense transformation, nonlinearity, and regularization into one reusable block.',
    intuitionZh: '把全连接变换、非线性激活和正则化组合成可复用模块。',
    principle: 'The dense layer mixes features, ReLU adds nonlinear capacity, and dropout reduces co-adaptation.',
    principleZh: '全连接层混合特征，ReLU 增加非线性表达能力，Dropout 减少共适应。',
    formula: 'y = Dropout(ReLU(Wx + b))',
    example: 'Expand the block to inspect or replace its Dense → ReLU → Dropout nodes.',
    exampleZh: '展开模块即可查看或替换其中的全连接 → ReLU → Dropout 节点。',
    visual: 'composite',
  }),
  conv_block: lesson({
    intuition: 'Package a common image feature-extraction stage.',
    intuitionZh: '把常见的图像特征提取阶段组合在一起。',
    principle: 'Convolution detects local patterns, normalization stabilizes them, ReLU gates them, and pooling downsamples.',
    principleZh: '卷积检测局部模式，归一化稳定特征，ReLU 进行非线性筛选，池化负责降采样。',
    formula: 'y = Pool(ReLU(BN(Conv(x))))',
    example: 'Use several blocks to progress from edges to higher-level image patterns.',
    exampleZh: '叠加多个卷积模块，可以从边缘逐步学习更高层图像模式。',
    visual: 'composite',
  }),
  residual_mlp_block: lesson({
    intuition: 'Learn a correction while keeping a direct shortcut for the original signal.',
    intuitionZh: '在保留原始信号捷径的同时，学习一个修正量。',
    principle: 'Residual addition improves gradient flow and lets the block fall back to an identity mapping.',
    principleZh: '残差相加改善梯度传播，并允许模块退化为恒等映射。',
    formula: 'y = x + F(x)',
    example: 'If F(x) learns zero, the block simply passes x through.',
    exampleZh: '如果 F(x) 学到零，模块就会直接传递 x。',
    visual: 'residual',
  }),
};

Object.entries(tutorialByOp).forEach(([op, tutorial]) => {
  tutorial.visual = op;
});

export function tutorialFor(manifest) {
  return tutorialByOp[manifest.op] ?? null;
}
