import React, { createContext, useCallback, useContext, useMemo, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ReactFlow, Background, Controls, Handle, MiniMap, Position, addEdge, useEdgesState, useNodesState } from '@xyflow/react';
import { motion } from 'framer-motion';
import '@xyflow/react/dist/style.css';

const PROJECT_VERSION = 1;
const languages = [
  { code: 'en', label: 'English' },
  { code: 'zh', label: '中文' },
];

const pluginRegistry = [
  {
    id: 'knn_node', name: { en: 'K-Nearest Neighbors', zh: 'K-近邻算法' }, category: 'Classification',
    description: { en: 'Classifies points by voting among nearby examples.', zh: '通过附近样本投票对数据点分类。' },
    inputs: [{ name: 'dataset', type: 'Table' }], outputs: [{ name: 'model', type: 'Model' }, { name: 'boundary', type: 'Mesh' }],
    properties: [{ key: 'k_value', label: { en: 'Number of Neighbors (K)', zh: '邻居数量 (K)' }, type: 'slider', min: 1, max: 21, step: 2, default: 3 }],
    pytorch_template: 'from sklearn.neighbors import KNeighborsClassifier\nmodel = KNeighborsClassifier(n_neighbors={k_value})',
  },
  {
    id: 'linear_regression_node', name: { en: 'Linear Regression', zh: '线性回归' }, category: 'Regression',
    description: { en: 'Fits a straight line to predict continuous values.', zh: '拟合直线来预测连续数值。' },
    inputs: [{ name: 'dataset', type: 'Table' }], outputs: [{ name: 'model', type: 'Model' }],
    properties: [{ key: 'learning_rate', label: { en: 'Learning Rate', zh: '学习率' }, type: 'slider', min: 0.001, max: 0.2, step: 0.001, default: 0.01 }],
    pytorch_template: 'import torch\nmodel = torch.nn.Linear(in_features=1, out_features=1)\noptimizer = torch.optim.SGD(model.parameters(), lr={learning_rate})',
  },
  {
    id: 'gradient_descent_node', name: { en: 'Gradient Descent', zh: '梯度下降' }, category: 'Optimization',
    description: { en: 'Iteratively updates parameters in the direction that reduces loss.', zh: '沿着降低损失的方向迭代更新参数。' },
    inputs: [{ name: 'model', type: 'Model' }], outputs: [{ name: 'trained_model', type: 'Model' }],
    properties: [{ key: 'epochs', label: { en: 'Training Epochs', zh: '训练轮数' }, type: 'slider', min: 10, max: 500, step: 10, default: 100 }],
    pytorch_template: 'for epoch in range({epochs}):\n    optimizer.zero_grad()\n    loss.backward()\n    optimizer.step()',
  },
];

const LanguageContext = createContext(null);
function LanguageProvider({ children }) {
  const [primary, setPrimary] = useState('en');
  const [secondary, setSecondary] = useState(null);
  const t = useCallback((value) => {
    if (typeof value === 'string') return value;
    const first = value?.[primary] ?? value?.en ?? Object.values(value ?? {})[0] ?? '';
    const second = secondary ? value?.[secondary] : null;
    return second && second !== first ? `${first} · ${second}` : first;
  }, [primary, secondary]);
  const setLanguages = ({ primary: nextPrimary, secondary: nextSecondary }) => {
    setPrimary(nextPrimary);
    setSecondary(nextSecondary && nextSecondary !== nextPrimary ? nextSecondary : null);
  };
  return <LanguageContext.Provider value={{ primary, secondary, setLanguages, t }}>{children}</LanguageContext.Provider>;
}
function useVividTranslation() { return useContext(LanguageContext); }

const defaults = (manifest) => Object.fromEntries(manifest.properties.map((property) => [property.key, property.default]));
const createNode = (manifest, index) => ({
  id: `${manifest.id}-${crypto.randomUUID()}`,
  type: 'pipelineNode',
  position: { x: 120 + index * 110, y: 90 + index * 90 },
  data: { label: manifest.name, manifest, parameters: defaults(manifest) },
});

function compilePipelineToPyTorch(nodes, edges) {
  const nodeById = new Map(nodes.map((node) => [node.id, node]));
  const indegree = new Map(nodes.map((node) => [node.id, 0]));
  const outgoing = new Map();
  edges.forEach((edge) => {
    outgoing.set(edge.source, [...(outgoing.get(edge.source) ?? []), edge.target]);
    indegree.set(edge.target, (indegree.get(edge.target) ?? 0) + 1);
  });
  const queue = nodes.filter((node) => indegree.get(node.id) === 0).map((node) => node.id);
  const ordered = [];
  while (queue.length) {
    const id = queue.shift();
    ordered.push(nodeById.get(id));
    (outgoing.get(id) ?? []).forEach((target) => {
      const next = indegree.get(target) - 1;
      indegree.set(target, next);
      if (next === 0) queue.push(target);
    });
  }
  if (ordered.length !== nodes.length) throw new Error('Pipeline graph contains a cycle.');
  return ['# Generated by VOLK-ML', '# Review tensor shapes and dataset bindings before running.', '', ...ordered.map((node, index) => `# Step ${index + 1}: ${node.data.manifest.name.en}\n${node.data.manifest.pytorch_template.replace(/\{(\w+)\}/g, (_, key) => node.data.parameters[key] ?? `{${key}}`)}`)].join('\n\n');
}

function downloadText(filename, content, type) {
  const url = URL.createObjectURL(new Blob([content], { type }));
  const anchor = document.createElement('a');
  anchor.href = url;
  anchor.download = filename;
  anchor.click();
  URL.revokeObjectURL(url);
}

function PipelineNode({ data, selected }) {
  const { t } = useVividTranslation();
  return <div className={`min-w-52 max-w-72 rounded-2xl border bg-white p-4 shadow-lg ${selected ? 'border-blue-500' : 'border-slate-200'}`}>
    {data.manifest.inputs.map((input, index) => <Handle key={input.name} type="target" position={Position.Left} id={input.name} style={{ top: 44 + index * 22 }} />)}
    <p className="text-xs font-semibold uppercase tracking-wide text-blue-600">{data.manifest.category}</p>
    <h3 className="mt-1 break-words text-base font-bold text-slate-900">{t(data.label)}</h3>
    <p className="mt-2 break-words text-sm text-slate-600">{t(data.manifest.description)}</p>
    <div className="mt-3 flex flex-wrap gap-1 text-[11px] text-slate-500">{data.manifest.outputs.map((output) => <span className="rounded-full bg-slate-100 px-2 py-1" key={output.name}>{output.name}: {output.type}</span>)}</div>
    {data.manifest.outputs.map((output, index) => <Handle key={output.name} type="source" position={Position.Right} id={output.name} style={{ top: 44 + index * 22 }} />)}
  </div>;
}

function LossChart({ values }) {
  if (!values.length) return <div className="grid h-40 place-items-center text-sm text-slate-400">Run the model to see loss</div>;
  const width = 520;
  const height = 160;
  const max = Math.max(...values, 0.0001);
  const points = values.map((value, index) => `${(index / Math.max(values.length - 1, 1)) * width},${height - (value / max) * (height - 12)}`).join(' ');
  return <svg viewBox={`0 0 ${width} ${height}`} className="h-40 w-full overflow-visible rounded-xl bg-slate-950 p-2" role="img" aria-label="Training loss curve">
    <polyline fill="none" stroke="#38bdf8" strokeWidth="4" strokeLinejoin="round" strokeLinecap="round" points={points} />
  </svg>;
}

function LanguageDialog({ open, onClose }) {
  const { primary, secondary, setLanguages } = useVividTranslation();
  const [draftPrimary, setDraftPrimary] = useState(primary);
  const [draftSecondary, setDraftSecondary] = useState(secondary ?? 'none');
  if (!open) return null;
  return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/45 p-4" onMouseDown={onClose}>
    <section className="w-full max-w-md rounded-3xl bg-white p-6 shadow-2xl" onMouseDown={(event) => event.stopPropagation()}>
      <div className="flex items-center justify-between"><h2 className="text-xl font-black">Language settings · 语言设置</h2><button className="rounded-full p-2 hover:bg-slate-100" onClick={onClose}>✕</button></div>
      <p className="mt-2 text-sm text-slate-500">Choose one language, or add any second language for parallel labels.</p>
      <label className="mt-5 block text-sm font-bold">Primary language
        <select className="mt-2 w-full rounded-xl border p-3" value={draftPrimary} onChange={(event) => { setDraftPrimary(event.target.value); if (draftSecondary === event.target.value) setDraftSecondary('none'); }}>
          {languages.map((language) => <option key={language.code} value={language.code}>{language.label}</option>)}
        </select>
      </label>
      <label className="mt-4 block text-sm font-bold">Parallel language
        <select className="mt-2 w-full rounded-xl border p-3" value={draftSecondary} onChange={(event) => setDraftSecondary(event.target.value)}>
          <option value="none">None · 单语言</option>
          {languages.filter((language) => language.code !== draftPrimary).map((language) => <option key={language.code} value={language.code}>{language.label}</option>)}
        </select>
      </label>
      <button className="mt-6 w-full rounded-2xl bg-blue-600 px-4 py-3 font-bold text-white" onClick={() => { setLanguages({ primary: draftPrimary, secondary: draftSecondary === 'none' ? null : draftSecondary }); onClose(); }}>Apply · 应用</button>
    </section>
  </div>;
}

function RunnerDialog({ open, onClose, nodes }) {
  const { t } = useVividTranslation();
  const [running, setRunning] = useState(false);
  const [losses, setLosses] = useState([]);
  const [result, setResult] = useState(null);
  if (!open) return null;
  const run = async () => {
    if (running) return;
    setRunning(true);
    setLosses([]);
    setResult(null);
    const linear = nodes.find((node) => node.data.manifest.id === 'linear_regression_node');
    const optimizer = nodes.find((node) => node.data.manifest.id === 'gradient_descent_node');
    const learningRate = linear?.data.parameters.learning_rate ?? 0.03;
    const epochs = optimizer?.data.parameters.epochs ?? 100;
    const samples = Array.from({ length: 60 }, (_, index) => {
      const x = -1 + (index / 59) * 2;
      return { x, y: 2 * x + 1 + Math.sin(index * 1.7) * 0.08 };
    });
    let weight = -0.5;
    let bias = 0;
    const history = [];
    for (let epoch = 0; epoch < epochs; epoch += 1) {
      let loss = 0;
      let dw = 0;
      let db = 0;
      samples.forEach(({ x, y }) => {
        const error = weight * x + bias - y;
        loss += error * error;
        dw += 2 * error * x;
        db += 2 * error;
      });
      loss /= samples.length;
      weight -= learningRate * (dw / samples.length);
      bias -= learningRate * (db / samples.length);
      history.push(loss);
      if (epoch % Math.max(1, Math.floor(epochs / 50)) === 0 || epoch === epochs - 1) {
        setLosses([...history]);
        await new Promise((resolve) => requestAnimationFrame(resolve));
      }
    }
    setResult({ weight, bias, loss: history.at(-1), epochs, learningRate });
    setRunning(false);
  };
  return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/50 p-4" onMouseDown={onClose}>
    <section className="max-h-[90vh] w-full max-w-2xl overflow-auto rounded-3xl bg-white p-6 shadow-2xl" onMouseDown={(event) => event.stopPropagation()}>
      <div className="flex items-start justify-between gap-4"><div><h2 className="text-xl font-black">{t({ en: 'Local CPU Lab', zh: '本地 CPU 实验室' })}</h2><p className="mt-1 text-sm text-slate-500">Real gradient descent in your browser. No data leaves this device.</p></div><button className="rounded-full p-2 hover:bg-slate-100" onClick={onClose}>✕</button></div>
      <div className="mt-5"><LossChart values={losses} /></div>
      {result && <div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-4">{Object.entries(result).map(([key, value]) => <div key={key} className="rounded-2xl bg-slate-100 p-3"><p className="text-xs uppercase text-slate-500">{key}</p><p className="mt-1 font-mono font-bold">{typeof value === 'number' ? value.toFixed(4) : value}</p></div>)}</div>}
      <p className="mt-4 text-xs text-slate-500">Prototype executor: linear regression + gradient descent. The execution registry can later add classification, neural-network layers, TensorFlow.js and WebGPU backends.</p>
      <button disabled={running} onClick={run} className="mt-5 w-full rounded-2xl bg-emerald-600 px-4 py-3 font-bold text-white disabled:opacity-60">{running ? 'Training…' : '▶ Run locally on CPU'}</button>
    </section>
  </div>;
}

function Workspace() {
  const { primary, secondary, setLanguages, t } = useVividTranslation();
  const [nodes, setNodes, onNodesChange] = useNodesState(pluginRegistry.slice(0, 2).map(createNode));
  const [edges, setEdges, onEdgesChange] = useEdgesState([]);
  const [selectedId, setSelectedId] = useState(nodes[0]?.id);
  const [leftOpen, setLeftOpen] = useState(true);
  const [rightOpen, setRightOpen] = useState(true);
  const [leftWidth, setLeftWidth] = useState(300);
  const [rightWidth, setRightWidth] = useState(340);
  const [libraryMode, setLibraryMode] = useState('detailed');
  const [query, setQuery] = useState('');
  const [languageOpen, setLanguageOpen] = useState(false);
  const [runnerOpen, setRunnerOpen] = useState(false);
  const [notice, setNotice] = useState('');
  const importRef = useRef(null);
  const selectedNode = nodes.find((node) => node.id === selectedId) ?? nodes[0];
  const filteredPlugins = useMemo(() => pluginRegistry.filter((plugin) => {
    const haystack = [plugin.category, ...Object.values(plugin.name), ...Object.values(plugin.description)].join(' ').toLowerCase();
    return haystack.includes(query.trim().toLowerCase());
  }), [query]);
  const grouped = useMemo(() => filteredPlugins.reduce((acc, plugin) => ({ ...acc, [plugin.category]: [...(acc[plugin.category] ?? []), plugin] }), {}), [filteredPlugins]);
  const onConnect = useCallback((connection) => setEdges((current) => addEdge(connection, current)), [setEdges]);
  const addPluginNode = (manifest) => { const node = createNode(manifest, nodes.length); setNodes((current) => [...current, node]); setSelectedId(node.id); };
  const updateParameter = (key, value) => setNodes((current) => current.map((node) => node.id === selectedNode?.id ? { ...node, data: { ...node.data, parameters: { ...node.data.parameters, [key]: value } } } : node));
  const exportCode = () => downloadText('volk_ml_pipeline.py', compilePipelineToPyTorch(nodes, edges), 'text/x-python');
  const exportProject = () => {
    const project = { format: 'VOLK-ML', version: PROJECT_VERSION, savedAt: new Date().toISOString(), language: { primary, secondary }, workspace: { libraryMode, leftWidth, rightWidth }, graph: { nodes, edges } };
    downloadText('volk_ml_project.json', JSON.stringify(project, null, 2), 'application/json');
    setNotice(t({ en: 'Project JSON saved', zh: '项目 JSON 已保存' }));
  };
  const importProject = async (event) => {
    const file = event.target.files?.[0];
    event.target.value = '';
    if (!file) return;
    try {
      const project = JSON.parse(await file.text());
      if (project.format !== 'VOLK-ML' || !Array.isArray(project.graph?.nodes) || !Array.isArray(project.graph?.edges)) throw new Error('Invalid VOLK-ML project');
      const restoredNodes = project.graph.nodes.map((node) => {
        const manifestId = node.data?.manifest?.id;
        const currentManifest = pluginRegistry.find((plugin) => plugin.id === manifestId) ?? node.data?.manifest;
        if (!currentManifest) throw new Error(`Unknown component: ${manifestId}`);
        return { ...node, type: 'pipelineNode', data: { ...node.data, label: currentManifest.name, manifest: currentManifest, parameters: { ...defaults(currentManifest), ...node.data?.parameters } } };
      });
      setNodes(restoredNodes);
      setEdges(project.graph.edges);
      setSelectedId(restoredNodes[0]?.id);
      if (project.language?.primary) setLanguages(project.language);
      if (project.workspace?.libraryMode) setLibraryMode(project.workspace.libraryMode);
      if (Number.isFinite(project.workspace?.leftWidth)) setLeftWidth(project.workspace.leftWidth);
      if (Number.isFinite(project.workspace?.rightWidth)) setRightWidth(project.workspace.rightWidth);
      setNotice(t({ en: 'Project imported successfully', zh: '项目导入成功' }));
    } catch (error) {
      setNotice(`${t({ en: 'Import failed', zh: '导入失败' })}: ${error.message}`);
    }
  };
  const startResize = (side, event) => {
    event.preventDefault();
    const startX = event.clientX;
    const initial = side === 'left' ? leftWidth : rightWidth;
    const move = (moveEvent) => {
      const delta = moveEvent.clientX - startX;
      const next = initial + (side === 'left' ? delta : -delta);
      (side === 'left' ? setLeftWidth : setRightWidth)(Math.min(520, Math.max(220, next)));
    };
    const stop = () => { window.removeEventListener('pointermove', move); window.removeEventListener('pointerup', stop); };
    window.addEventListener('pointermove', move);
    window.addEventListener('pointerup', stop);
  };

  const asideBase = 'fixed bottom-3 top-[76px] z-30 overflow-auto rounded-3xl border border-white/80 bg-white/95 p-4 shadow-2xl backdrop-blur transition-transform lg:static lg:z-auto lg:h-auto lg:rounded-3xl lg:bg-white/85 lg:shadow-xl';
  return <div className="flex h-[100dvh] flex-col overflow-hidden bg-gradient-to-br from-sky-50 via-white to-indigo-100">
    <header className="z-40 flex min-h-[64px] items-center justify-between gap-3 border-b border-white/70 bg-white/90 px-3 py-2 shadow-sm backdrop-blur sm:px-5">
      <div className="min-w-0"><h1 className="text-xl font-black text-slate-950 sm:text-2xl">VOLK-ML</h1><p className="hidden truncate text-xs text-slate-600 sm:block">{t({ en: 'Visual bridges for PyTorch & TensorFlow', zh: '连接 PyTorch 与 TensorFlow 的可视化桥梁' })}</p></div>
      <nav className="flex items-center gap-1.5 overflow-x-auto text-sm">
        <button className="rounded-xl bg-slate-100 px-3 py-2 font-bold" onClick={() => setLeftOpen((value) => !value)}>☰ <span className="hidden sm:inline">Blocks</span></button>
        <button className="rounded-xl bg-slate-100 px-3 py-2 font-bold" onClick={() => setRightOpen((value) => !value)}>⚙ <span className="hidden sm:inline">Params</span></button>
        <button className="rounded-xl bg-slate-100 px-3 py-2 font-bold" onClick={exportProject}>↓ <span className="hidden md:inline">JSON</span></button>
        <button className="rounded-xl bg-slate-100 px-3 py-2 font-bold" onClick={() => importRef.current?.click()}>↑ <span className="hidden md:inline">Import</span></button>
        <input ref={importRef} type="file" accept="application/json,.json" className="hidden" onChange={importProject} />
        <button className="rounded-xl bg-slate-100 px-3 py-2 font-bold" onClick={() => setLanguageOpen(true)}>文</button>
        <button className="rounded-xl bg-emerald-600 px-3 py-2 font-bold text-white" onClick={() => setRunnerOpen(true)}>▶ <span className="hidden sm:inline">Run</span></button>
      </nav>
    </header>

    <main className="relative grid min-h-0 flex-1 grid-cols-[0_minmax(0,1fr)_0] gap-3 p-3 lg:grid-cols-[var(--left-panel)_minmax(0,1fr)_var(--right-panel)]" style={{ '--left-panel': `${leftOpen ? leftWidth : 0}px`, '--right-panel': `${rightOpen ? rightWidth : 0}px` }}>
      <motion.aside initial={false} animate={{ x: leftOpen ? 0 : '-110%' }} style={{ width: `min(${leftWidth}px, calc(100vw - 24px))` }} className={`${asideBase} left-3 lg:transform-none ${leftOpen ? 'lg:block' : 'lg:hidden'}`}>
        <div className="flex items-center justify-between gap-2"><h2 className="text-lg font-black">{t({ en: 'Components', zh: '组件库' })}</h2><button className="rounded-lg p-2 hover:bg-slate-100" onClick={() => setLeftOpen(false)}>✕</button></div>
        <div className="mt-3 flex gap-2"><div className="relative min-w-0 flex-1"><span className="absolute left-3 top-2.5">⌕</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder={t({ en: 'Search components', zh: '搜索组件' })} className="w-full rounded-xl border border-slate-200 py-2 pl-9 pr-3 text-sm outline-none focus:border-blue-500" /></div><button className="rounded-xl border px-3 text-sm font-bold" onClick={() => setLibraryMode((mode) => mode === 'compact' ? 'detailed' : 'compact')}>{libraryMode === 'compact' ? '☷' : '≡'}</button></div>
        <label className="mt-3 flex items-center gap-3 text-xs text-slate-500"><span>Width</span><input type="range" min="220" max="520" value={leftWidth} onChange={(event) => setLeftWidth(Number(event.target.value))} className="min-w-0 flex-1 accent-blue-600" /><span>{leftWidth}px</span></label>
        <p className="mt-2 text-xs text-slate-400">{filteredPlugins.length} components · {libraryMode}</p>
        <div className="mt-4 space-y-5">{Object.entries(grouped).map(([category, plugins]) => <section key={category}><h3 className="mb-2 text-xs font-bold uppercase tracking-wider text-slate-500">{category}</h3><div className="space-y-2">{plugins.map((plugin) => <button key={plugin.id} onClick={() => addPluginNode(plugin)} className={`w-full rounded-2xl border border-slate-200 bg-white text-left shadow-sm transition hover:border-blue-400 hover:shadow-md ${libraryMode === 'compact' ? 'px-3 py-2' : 'p-3'}`}><span className="block break-words font-semibold text-slate-900">{t(plugin.name)}</span>{libraryMode === 'detailed' && <span className="mt-1 block break-words text-xs text-slate-500">{t(plugin.description)}</span>}</button>)}</div></section>)}</div>
        <div className="absolute bottom-8 right-0 top-8 hidden w-2 cursor-col-resize touch-none lg:block" onPointerDown={(event) => startResize('left', event)} />
      </motion.aside>

      <section className="col-start-2 overflow-hidden rounded-3xl border border-white/80 bg-white shadow-xl"><ReactFlow nodes={nodes} edges={edges} onNodesChange={onNodesChange} onEdgesChange={onEdgesChange} onConnect={onConnect} onNodeClick={(_, node) => setSelectedId(node.id)} nodeTypes={{ pipelineNode: PipelineNode }} fitView><Background /><MiniMap pannable zoomable /><Controls /></ReactFlow></section>

      <motion.aside initial={false} animate={{ x: rightOpen ? 0 : '110%' }} style={{ width: `min(${rightWidth}px, calc(100vw - 24px))` }} className={`${asideBase} right-3 lg:transform-none ${rightOpen ? 'lg:block' : 'lg:hidden'}`}>
        <div className="flex items-center justify-between gap-2"><h2 className="text-lg font-black">{t({ en: 'Parameters', zh: '参数设置' })}</h2><button className="rounded-lg p-2 hover:bg-slate-100" onClick={() => setRightOpen(false)}>✕</button></div>
        <label className="mt-3 flex items-center gap-3 text-xs text-slate-500"><span>Width</span><input type="range" min="220" max="520" value={rightWidth} onChange={(event) => setRightWidth(Number(event.target.value))} className="min-w-0 flex-1 accent-blue-600" /><span>{rightWidth}px</span></label>
        {selectedNode ? <div className="mt-4 space-y-5"><div className="rounded-2xl bg-blue-50 p-4"><p className="text-xs font-bold uppercase text-blue-600">{selectedNode.data.manifest.category}</p><h3 className="break-words text-xl font-black text-slate-900">{t(selectedNode.data.label)}</h3></div>{selectedNode.data.manifest.properties.map((property) => <label key={property.key} className="block rounded-2xl border border-slate-200 bg-white p-4"><span className="block break-words text-sm font-bold text-slate-800">{t(property.label)}</span><input className="mt-3 w-full accent-blue-600" type={property.type === 'slider' ? 'range' : 'text'} min={property.min} max={property.max} step={property.step} value={selectedNode.data.parameters[property.key]} onChange={(event) => updateParameter(property.key, property.type === 'text' ? event.target.value : Number(event.target.value))} /><span className="mt-2 block text-sm text-slate-500">{selectedNode.data.parameters[property.key]}</span></label>)}<button onClick={exportCode} className="w-full rounded-2xl bg-slate-950 px-4 py-3 font-bold text-white shadow-lg transition hover:bg-blue-700">🛠️ {t({ en: 'Export PyTorch Code', zh: '导出 PyTorch 代码' })}</button></div> : <p className="mt-6 text-sm text-slate-500">Select a component to edit it.</p>}
        <div className="absolute bottom-8 left-0 top-8 hidden w-2 cursor-col-resize touch-none lg:block" onPointerDown={(event) => startResize('right', event)} />
      </motion.aside>
    </main>
    {notice && <button onClick={() => setNotice('')} className="fixed bottom-5 left-1/2 z-50 -translate-x-1/2 rounded-full bg-slate-950 px-5 py-3 text-sm font-bold text-white shadow-2xl">{notice} · ✕</button>}
    <LanguageDialog open={languageOpen} onClose={() => setLanguageOpen(false)} />
    <RunnerDialog open={runnerOpen} onClose={() => setRunnerOpen(false)} nodes={nodes} />
  </div>;
}

createRoot(document.getElementById('root')).render(<LanguageProvider><Workspace /></LanguageProvider>);
