import React, { createContext, useCallback, useContext, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ReactFlow, Background, Controls, Handle, Position, addEdge, useEdgesState, useNodesState } from '@xyflow/react';
import { motion } from 'framer-motion';
import '@xyflow/react/dist/style.css';

const pluginRegistry = [
  {
    id: 'knn_node', name: { en: 'K-Nearest Neighbors', zh: 'K-近邻算法' }, category: 'Classification',
    description: { en: 'Classifies points by voting among nearby examples.', zh: '通过附近样本投票对数据点分类。' },
    inputs: [{ name: 'dataset', type: 'Table' }], outputs: [{ name: 'model', type: 'Model' }, { name: 'boundary', type: 'Mesh' }],
    properties: [{ key: 'k_value', label: { en: 'Number of Neighbors (K)', zh: '邻居数量 (K)' }, type: 'slider', min: 1, max: 21, step: 2, default: 3 }],
    pytorch_template: 'from sklearn.neighbors import KNeighborsClassifier\nmodel = KNeighborsClassifier(n_neighbors={k_value})',
  },
  {
    id: 'linear_regression_node', name: { en: 'Linear Regression', zh: '线性回归' }, category: 'Regression',
    description: { en: 'Fits a straight line to predict continuous values.', zh: '拟合直线来预测连续数值。' },
    inputs: [{ name: 'dataset', type: 'Table' }], outputs: [{ name: 'model', type: 'Model' }],
    properties: [{ key: 'learning_rate', label: { en: 'Learning Rate', zh: '学习率' }, type: 'slider', min: 0.001, max: 0.2, step: 0.001, default: 0.01 }],
    pytorch_template: 'import torch\nmodel = torch.nn.Linear(in_features=1, out_features=1)\noptimizer = torch.optim.SGD(model.parameters(), lr={learning_rate})',
  },
  {
    id: 'gradient_descent_node', name: { en: 'Gradient Descent', zh: '梯度下降' }, category: 'Optimization',
    description: { en: 'Iteratively updates parameters in the direction that reduces loss.', zh: '沿着降低损失的方向迭代更新参数。' },
    inputs: [{ name: 'model', type: 'Model' }], outputs: [{ name: 'trained_model', type: 'Model' }],
    properties: [{ key: 'epochs', label: { en: 'Training Epochs', zh: '训练轮数' }, type: 'slider', min: 10, max: 500, step: 10, default: 100 }],
    pytorch_template: 'for epoch in range({epochs}):\n    optimizer.zero_grad()\n    loss.backward()\n    optimizer.step()',
  },
];

const LanguageContext = createContext(null);
function LanguageProvider({ children }) {
  const [mode, setMode] = useState('en');
  const t = useCallback((value) => mode === 'zh' ? value.zh : mode === 'parallel' ? `${value.zh} (${value.en})` : value.en, [mode]);
  return <LanguageContext.Provider value={{ mode, setMode, t }}>{children}</LanguageContext.Provider>;
}
function useVividTranslation() { return useContext(LanguageContext); }
const defaults = (manifest) => Object.fromEntries(manifest.properties.map((property) => [property.key, property.default]));
const createNode = (manifest, index) => ({ id: `${manifest.id}-${crypto.randomUUID()}`, type: 'pipelineNode', position: { x: 120 + index * 110, y: 90 + index * 90 }, data: { label: manifest.name, manifest, parameters: defaults(manifest) } });

function compilePipelineToPyTorch(nodes, edges) {
  const nodeById = new Map(nodes.map((node) => [node.id, node]));
  const indegree = new Map(nodes.map((node) => [node.id, 0]));
  const outgoing = new Map();
  edges.forEach((edge) => { outgoing.set(edge.source, [...(outgoing.get(edge.source) ?? []), edge.target]); indegree.set(edge.target, (indegree.get(edge.target) ?? 0) + 1); });
  const queue = nodes.filter((node) => indegree.get(node.id) === 0).map((node) => node.id);
  const ordered = [];
  while (queue.length) {
    const id = queue.shift(); ordered.push(nodeById.get(id));
    (outgoing.get(id) ?? []).forEach((target) => { const next = indegree.get(target) - 1; indegree.set(target, next); if (next === 0) queue.push(target); });
  }
  if (ordered.length !== nodes.length) throw new Error('Pipeline graph contains a cycle.');
  return ['# Generated by VOLK-ML', '# Review tensor shapes and dataset bindings before running.', '', ...ordered.map((node, index) => `# Step ${index + 1}: ${node.data.manifest.name.en}\n${node.data.manifest.pytorch_template.replace(/\{(\w+)\}/g, (_, key) => node.data.parameters[key] ?? `{${key}}`)}`)].join('\n\n');
}

function PipelineNode({ data, selected }) {
  const { t } = useVividTranslation();
  return <div className={`min-w-56 max-w-72 rounded-2xl border bg-white p-4 shadow-lg ${selected ? 'border-blue-500' : 'border-slate-200'}`}>
    {data.manifest.inputs.map((input, index) => <Handle key={input.name} type="target" position={Position.Left} id={input.name} style={{ top: 44 + index * 22 }} />)}
    <p className="text-xs font-semibold uppercase tracking-wide text-blue-600">{data.manifest.category}</p>
    <h3 className="mt-1 break-words text-base font-bold text-slate-900">{t(data.label)}</h3>
    <p className="mt-2 break-words text-sm text-slate-600">{t(data.manifest.description)}</p>
    <div className="mt-3 flex flex-wrap gap-1 text-[11px] text-slate-500">{data.manifest.outputs.map((output) => <span className="rounded-full bg-slate-100 px-2 py-1" key={output.name}>{output.name}: {output.type}</span>)}</div>
    {data.manifest.outputs.map((output, index) => <Handle key={output.name} type="source" position={Position.Right} id={output.name} style={{ top: 44 + index * 22 }} />)}
  </div>;
}

function Workspace() {
  const { mode, setMode, t } = useVividTranslation();
  const [nodes, setNodes, onNodesChange] = useNodesState(pluginRegistry.slice(0, 2).map(createNode));
  const [edges, setEdges, onEdgesChange] = useEdgesState([]);
  const [selectedId, setSelectedId] = useState(nodes[0]?.id);
  const selectedNode = nodes.find((node) => node.id === selectedId) ?? nodes[0];
  const grouped = useMemo(() => pluginRegistry.reduce((acc, plugin) => ({ ...acc, [plugin.category]: [...(acc[plugin.category] ?? []), plugin] }), {}), []);
  const onConnect = useCallback((connection) => setEdges((eds) => addEdge(connection, eds)), [setEdges]);
  const addPluginNode = (manifest) => { const node = createNode(manifest, nodes.length); setNodes((current) => [...current, node]); setSelectedId(node.id); };
  const updateParameter = (key, value) => setNodes((current) => current.map((node) => node.id === selectedNode?.id ? { ...node, data: { ...node.data, parameters: { ...node.data.parameters, [key]: value } } } : node));
  const exportCode = () => { const url = URL.createObjectURL(new Blob([compilePipelineToPyTorch(nodes, edges)], { type: 'text/x-python' })); const a = document.createElement('a'); a.href = url; a.download = 'volk_ml_pipeline.py'; a.click(); URL.revokeObjectURL(url); };

  return <div className="flex h-screen flex-col overflow-hidden bg-gradient-to-br from-sky-50 via-white to-indigo-100">
    <header className="flex flex-wrap items-center justify-between gap-4 border-b border-white/70 bg-white/85 px-6 py-4 shadow-sm backdrop-blur"><div><h1 className="text-2xl font-black text-slate-950">VOLK-ML</h1><p className="text-sm text-slate-600">{t({ en: 'Vivid Online Learning Kit for Machine Learning', zh: '机器学习可视化在线学习工具包' })}</p></div><div className="flex rounded-full bg-slate-100 p-1 text-sm font-semibold">{['en', 'zh', 'parallel'].map((option) => <button key={option} onClick={() => setMode(option)} className={`rounded-full px-4 py-2 transition ${mode === option ? 'bg-blue-600 text-white shadow' : 'text-slate-600 hover:bg-white'}`}>{option === 'en' ? 'English' : option === 'zh' ? '中文' : 'Parallel 并行'}</button>)}</div></header>
    <main className="grid min-h-0 flex-1 grid-cols-[300px_minmax(0,1fr)_340px] gap-4 p-4">
      <motion.aside initial={{ x: -24, opacity: 0 }} animate={{ x: 0, opacity: 1 }} className="overflow-auto rounded-3xl border border-white/80 bg-white/85 p-4 shadow-xl"><h2 className="text-lg font-bold text-slate-900">{t({ en: 'Playbook & Plugin Blocks', zh: '学习指南与插件模块' })}</h2><p className="mt-2 text-sm text-slate-600">{t({ en: 'Add blocks from discovered manifest folders. New folders under src/plugins appear here automatically in the typed build.', zh: '从发现的 manifest 文件夹添加模块。类型化构建会自动显示 src/plugins 下的新文件夹。' })}</p><div className="mt-4 space-y-5">{Object.entries(grouped).map(([category, plugins]) => <section key={category}><h3 className="mb-2 text-xs font-bold uppercase tracking-wider text-slate-500">{category}</h3><div className="space-y-2">{plugins.map((plugin) => <button key={plugin.id} onClick={() => addPluginNode(plugin)} className="w-full rounded-2xl border border-slate-200 bg-white p-3 text-left shadow-sm transition hover:border-blue-400 hover:shadow-md"><span className="block break-words font-semibold text-slate-900">{t(plugin.name)}</span><span className="mt-1 block break-words text-xs text-slate-500">{t(plugin.description)}</span></button>)}</div></section>)}</div></motion.aside>
      <section className="overflow-hidden rounded-3xl border border-white/80 bg-white shadow-xl"><ReactFlow nodes={nodes} edges={edges} onNodesChange={onNodesChange} onEdgesChange={onEdgesChange} onConnect={onConnect} onNodeClick={(_, node) => setSelectedId(node.id)} nodeTypes={{ pipelineNode: PipelineNode }} fitView><Background /><Controls /></ReactFlow></section>
      <motion.aside initial={{ x: 24, opacity: 0 }} animate={{ x: 0, opacity: 1 }} className="overflow-auto rounded-3xl border border-white/80 bg-white/85 p-4 shadow-xl"><h2 className="text-lg font-bold text-slate-900">{t({ en: 'Interactive Parameters', zh: '交互参数' })}</h2>{selectedNode && <div className="mt-4 space-y-5"><div className="rounded-2xl bg-blue-50 p-4"><p className="text-xs font-bold uppercase text-blue-600">{selectedNode.data.manifest.category}</p><h3 className="break-words text-xl font-black text-slate-900">{t(selectedNode.data.label)}</h3></div>{selectedNode.data.manifest.properties.map((property) => <label key={property.key} className="block rounded-2xl border border-slate-200 bg-white p-4"><span className="block break-words text-sm font-bold text-slate-800">{t(property.label)}</span><input className="mt-3 w-full accent-blue-600" type={property.type === 'slider' ? 'range' : 'text'} min={property.min} max={property.max} step={property.step} value={selectedNode.data.parameters[property.key]} onChange={(event) => updateParameter(property.key, property.type === 'text' ? event.target.value : Number(event.target.value))} /><span className="mt-2 block text-sm text-slate-500">{selectedNode.data.parameters[property.key]}</span></label>)}<button onClick={exportCode} className="w-full rounded-2xl bg-slate-950 px-4 py-3 font-bold text-white shadow-lg transition hover:bg-blue-700">🛠️ {t({ en: 'Export PyTorch Code', zh: '编译为 PyTorch 代码' })}</button></div>}</motion.aside>
    </main>
  </div>;
}

createRoot(document.getElementById('root')).render(<LanguageProvider><Workspace /></LanguageProvider>);
